def show_prize(prize_num, receipt_prizenum):
    # print(receipt_prizenum)
    if(prize_num == str(receipt_prizenum['superPrizeNo'])):
        win = 'super'
        money = receipt_prizenum['superPrizeAmt']
    elif(prize_num == str(receipt_prizenum['spcPrizeNo'])):
        win = 'special'
        money = receipt_prizenum['spcPrizeAmt']
    elif(prize_num == str(receipt_prizenum['spcPrizeNo2'])):
        win = 'special'
        money = receipt_prizenum['spcPrizeAmt']
    elif(prize_num == str(receipt_prizenum['spcPrizeNo3'])):
        win = 'special'
        money = receipt_prizenum['spcPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo1'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo2'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo3'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo4'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo5'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo6'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo7'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo8'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo9'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num == str(receipt_prizenum['firstPrizeNo10'])):
        win = 1
        money = receipt_prizenum['firstPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo1'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo2'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo3'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo4'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo5'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo6'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo7'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo8'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo9'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[1:] == str(receipt_prizenum['firstPrizeNo10'])):
        win = 2
        money = receipt_prizenum['secondPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo1'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo2'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo3'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo4'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo5'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo6'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo7'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo8'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo9'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[2:] == str(receipt_prizenum['firstPrizeNo10'])):
        win = 3
        money = receipt_prizenum['thirdPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo1'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo2'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo3'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo4'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo5'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo6'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo7'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo8'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo9'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[3:] == str(receipt_prizenum['firstPrizeNo10'])):
        win = 4
        money = receipt_prizenum['fourthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo1'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo2'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo3'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo4'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo5'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo6'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo7'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo8'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo9'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[4:] == str(receipt_prizenum['firstPrizeNo10'])):
        win = 5
        money = receipt_prizenum['fifthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo1'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo2'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo3'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo4'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo5'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo6'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo7'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo8'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo9'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['firstPrizeNo10'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['sixthPrizeNo1'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['sixthPrizeNo2'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['sixthPrizeNo3'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['sixthPrizeNo4'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['sixthPrizeNo5'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    elif(prize_num[5:] == str(receipt_prizenum['sixthPrizeNo6'])):
        win = 6
        money = receipt_prizenum['sixthPrizeAmt']
    else:
        win = 0
        money = 0

    return win, money
